### ISSUE TITLE
Refactor ExtensionService.execute()

### ISSUE THREAD

**Issue by johanherman** [Molmed/clarity-ext#47]
When reviewing https://github.com/Molmed/clarity-snpseq/pull/29 I tried to get a quick and brief overview of the `clarity-ext validate` to get a sense of what it would do. 

I stumbled across the `ExtensionService.execute()` method (https://github.com/Molmed/clarity-ext/blob/432d4304d6c1040b6b0e0a8f76e09d4c70895829/clarity_ext/extensions.py#L91) that seems to clock in at an awful lot of lines of code, with lots of nested for loops and if statements. 

It would be nice to have this method re-factored somehow at some stage to make it easier to understand (and to extend/test/etc).

**Comment by withrocks** [comment]
I agree, this function is really bloated, it hasn't been refactored at all after the hack/prototype stage. I've added a tech-debt ticket in JIRA.

**Comment by withrocks** [comment]
This method has been refactored.
